Repository APIStear/FETEC-News, pull requests merged in 2021-05, with the labels that each got.

#2 Adds Boilerplate for client and server
  .env.config
  README.md
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  package-lock.json
  package.json
  server/app.js
  server/config/README.md
  server/controllers/README.md
  server/middleware/README.md
  server/models/README.md
  server/package-lock.json
  server/package.json
  server/routes/README.md
  server/services/README.md
Labels: documentation, enhancement

#32 Hacer reservaciones v1
  server/controllers/event.js
  server/models/event.js
  server/routes/event.js
Labels: back-end

#30 Login register
  .env.config
  client/.env.config
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/Header.js
  client/src/PageFooter.js
  client/src/SideDrawer.js
  client/src/SignIn.js
  client/src/Theme.js
  client/src/TokenUtilities.js
  server/app.js
  server/controllers/auth.js
  server/middleware/errorHandler.js
  server/middleware/sendAsJson.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/auth.js
Labels: back-end, front-end

#35 View event
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/EventView.js
  client/src/Header.js
  client/src/PrivateRoute.js
  client/src/SignIn.js
  server/controllers/event.js
  server/middleware/roleMiddleware.js
  server/models/event.js
  server/models/user.js
  server/routes/event.js
Labels: front-end

#39 Fixes undetected merge conflict
  server/controllers/event.js
  server/models/event.js
Labels: bug
