Repository APIStear/FETEC-News, pull requests merged in 2021-06, with the labels that each got.

#36 Create events
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/EventNew.css
  client/src/EventNew.js
  package-lock.json
  package.json
Labels: enhancement, front-end

#37 All events
  client/src/AllEvents.css
  client/src/AllEvents.js
  client/src/App.js
  package-lock.json
  package.json
Labels: enhancement, front-end

#47 Dashboard
  client/package-lock.json
  client/package.json
  client/public/Ejecutivo_VerticalBlanco.png
  client/public/ejecutivo azul-01.png
  client/public/ejecutivoHorizontal_negro.png
  client/public/ejecutivoVertical_negro.png
  client/public/horizontal blanco.png
  client/public/index.html
  client/public/logo_blue.png
  client/src/AdminDashboard.js
  client/src/AllEvents.js
  client/src/App.js
  client/src/Dashboard.js
  client/src/EventList.js
  client/src/EventNew.css
  client/src/EventNew.js
  client/src/EventView.js
  client/src/Header.js
  client/src/PageFooter.js
  client/src/PrivateRoute.js
  client/src/Searchbar.js
  client/src/SignIn.js
  client/src/UserDashboard.js
  server/controllers/auth.js
  server/controllers/user.js
  server/models/user.js
Labels: front-end

#40 Delete event
  client/src/AllEvents.css
  client/src/AllEvents.js
  client/src/App.js
  client/src/EventView.js
  package-lock.json
  package.json
  server/controllers/event.js
  server/models/event.js
Labels: enhancement, front-end

#53 Fixes event images on new event
  client/src/App.js
  client/src/EventNew.js
  server/controllers/event.js
Labels: back-end, front-end

#49 Arreglando cositas
  client/public/index.html
  client/src/Admin.js
  client/src/Dashboard.js
  client/src/EditEvent.js
  client/src/EventList.js
  client/src/EventNew.js
  client/src/EventView.js
  client/src/Home.js
  client/src/PageFooter.js
  client/src/SignIn.js
Labels: bug, front-end

#54 Search fix
  client/src/AdminDashboard.js
  client/src/AllEvents.js
  client/src/EditEvent.js
  client/src/EventList.js
  client/src/EventNew.js
  client/src/EventView.js
  client/src/Home.js
  client/src/RSVPtable.js
  client/src/SignIn.js
Labels: bug
